# Femc Driver
# Copyright (C) 2011-2018 Pauli Saksa
#
# Licensed under The MIT License, see file LICENSE.txt in this source tree.

define gen-awk
	@echo -e 'GEN:\t' $@
	gawk -f $^ > $@
endef

%.gen.cc : %.cc.awk %.cc.txt ;    $(gen-awk)
%.gen.hh : %.hh.awk %.hh.txt ;    $(gen-awk)
%_gen.inc : %.inc.awk %.inc.txt ; $(gen-awk)
gen.% : %.awk %.txt ;             $(gen-awk)
